language: cpp

git:
  depth: false #shallow clone causes problem with tags
  
addons:
  apt:
    update: true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIG=Release
  - BUILD_CONFIG=Debug
  
matrix:
  include: #extra matrix entries for docker builds
    #Rpi Release
    - env: BUILD_CONFIG=Release DOCKER_BUILD=Rpi
      services:
        - docker
    #Rpi Debug
    - env: BUILD_CONFIG=Debug DOCKER_BUILD=Rpi
      services:
        - docker
  exclude:
    #Travis docs say on osx gcc is an alias for clang anyway
    - os: osx
      compiler: clang

branches:
  only:
    - develop
    - master
    - /^release\/.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*$/

dist: xenial

install:
  - mkdir build && cd build
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install libmodbus libmicrohttpd
    elif [ -z "$DOCKER_BUILD" ]; then
      sudo apt-get install -y libmodbus5 libmodbus-dev libmicrohttpd10 libmicrohttpd-dev
    fi
  - |
    if [ "$DOCKER_BUILD" == "Rpi" ]; then
      sudo apt-get install -y qemu-user qemu-user-static g++-arm-linux-gnueabihf
      docker pull resin/rpi-raspbian
      DOCK=$(docker run -d -v $(pwd):/tmp/build -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static --rm -ti resin/rpi-raspbian:latest)
      docker exec -i $DOCK sh -c "apt-get update && apt-get install -y libmodbus5 libmodbus-dev libmicrohttpd10 libmicrohttpd-dev"
      mkdir sysroot
      docker cp $DOCK:/usr sysroot/
      export RPI_SYSROOT=$(pwd)/sysroot/
      export RUN="docker exec --interactive --workdir /tmp/build $DOCK"
      export STOP="docker stop $DOCK"
      export TOOLCHAIN_OPT="-DCMAKE_TOOLCHAIN_FILE=../rpi-toolchain.cmake"
    fi

script: 
  - cmake -DFULL=ON -DCMAKE_BUILD_TYPE=$BUILD_CONFIG $TOOLCHAIN_OPT ..
  - make
  - make package
  - $RUN build/ODC_tests
  #- $RUN build/DNP3Port_tests #opendnp3 bug makes this hang at the moment
  - $RUN build/MD3Port_tests
  - $STOP

deploy:
  provider: releases
  api_key:
    secure: "a1Vm3l2QwXhwDoFpQn1Rw6BEL+gHHDlSAL5C43IWjr52qPRBL/qiQi9DBSrb4421M01QQtfxHOAxVs7bcM3oZ6oTeqy4vVHA3oqMhDtlVrt0Om4tlyLdY8kuSM/Hxm5G6WPYcgIj2ABMoX0PxpEftgrEtqa8E/cu8WkSP1Hmuv5RC5fJ+TmLHTTW7KxRSKZ9clmjWzRgLyrLYB+eS3HFfo64XW98XHkop9U+rb7+NQ9E4oZ9gVXmPYwEG805lNePAhyJ+EZ6NAMwY0HFeNj5JRt73EFtokYaLTW+drf7zUnptT9grquCpu16EbmEnUrgdJfUKjZHUAuBu6vYGLmM1SJ9PcS9+PGnGqhKyIZhSRFZCeCH5//gc3sh+Yp7NxT+6IrqsOKVitNoeiXykpk4MwCefuxvB5kDboxic8vxniSp+awnlzmwyKHP/aDCUANHpkQ+uNHnpA7Ev+zFeZnsDoDmcrzT39pWZav23ofP4c7H7MsgjQV/SWutHp91Bqs8AR2sBRpXl6FbLKIMrgXUQWd52lsSGWUUW042KddzGlfiWPV24P642AI40LbkPD1yD4FStH/KniA+9q0xvKeDqGqSB/8IrH0ZUxB/pCrHbsLl0R77Wi2PmYYIT+LGL58UxaJzMr+CyMTW05HH6/ruM4pUXzSMes7GC7cdJs2D/g8="
  file_glob: true
  file: opendatacon-*.*.*-*-*-*-*-*.sh
  name: "opendatacon ${TRAVIS_TAG}"
  skip_cleanup: true
  on:
    tags: true
    compiler: gcc
  
