language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - develop
    - master
    - /^release\/.*$/

dist: xenial

install: 
  - sudo apt update
  - sudo apt install -qq libmodbus5 libmodbus-dev libmicrohttpd10 libmicrohttpd-dev

script: 
  - mkdir build && cd build && cmake -DFULL=ON ..
  - make
  #- make package #can turn this on when we do a deploy step
  - build/ODC_tests
  #- build/DNP3Port_tests #opendnp3 bug makes this hang at the moment
  - build/MD3Port_tests
  
