language: cpp

git:
  depth: false #shallow clone causes problem with tags

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIG=Release
  - BUILD_CONFIG=Debug

branches:
  only:
    - develop
    - master
    - /^release\/.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*$/

dist: xenial

matrix:
  exclude:
    - os: osx
      compiler: clang #Travis docs say on osx gcc is an alias for clang anyway

addons:
  apt:
    packages:
      - libmodbus5
      - libmodbus-dev
      - libmicrohttpd10
      - libmicrohttpd-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmodbus libmicrohttpd; fi

script: 
  - mkdir build && cd build && cmake -DFULL=ON -DCMAKE_BUILD_TYPE=$BUILD_CONFIG ..
  - make
  - make package
  - build/ODC_tests
  #- build/DNP3Port_tests #opendnp3 bug makes this hang at the moment
  - build/MD3Port_tests

deploy:
  provider: releases
  api_key:
    secure: "gXal83bNkvvf1GZp+yt9OWY+PzNIf8Q5fG0p1S4E9aHakrPjWZ7L283cOjjBY5QlX0dLHYSAulqg8NrBH+1K7RzJ9Ig0s0ay2FixolotjQgQwA3oo3nBR5LvWTvp8l6f9IQwM8y7WA3MvFwwq8Wpq8NbMVR9fRiPKOGIqtCxd7bNhASl5BI4bS4ebrXX4PVox5mpxu2kQTlN7GUo5G6l8fFRh4yeDe4iWOzhO1gUmOJLZlbEwhUHcTYhZrJy4riNgc8dv6INUuGmaqQNdqIhxA5f0xKivn+eYATYBs61S7XqP+vxvZt8rvZVd//CDxLxkaoyD7wS4w6CWQUni10Fommv0WT6KN3YD6nC9Z1bv/NLbM1KC1j5CyN/laSmpxSuycVbJoKaJ0SjXqQa1I4jMrLPRA/zLOhfYwNr5TnBsCbf/fLWp7cDBsqABIrO54W+3CVXwks+O7QQFk3M0fWTMntVSHmCVFPkMxLgUOsI1HpcXYdZd8GQQkF6oKEhnEwzgCL9jePWFwTBpwP+PkWePkRMetZmq03QWvNfqZja/gNKvxEz8DTAVdnQFuxd+5bWZH1gT29FuFvTqPpnD9i4Wu2HmazjVoq88am4JbgI5I7UXdDIiiLHGKgrO44VHSwP6vxNkTQ5QRexHtXQARe+qUovRl8lJOwYyN21P+EfcPg="
  file_glob: true
  file: opendatacon-*.*.*-*-*-*-*-*.sh
  name: "opendatacon ${TRAVIS_TAG}"
  skip_cleanup: true
  on:
    tags: true
    compiler: gcc
  
