language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - develop
    - master
    - /^release\/.*$/

dist: xenial

addons:
  apt:
    packages:
      - libmodbus5
      - libmodbus-dev
      - libmicrohttpd10
      - libmicrohttpd-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmodbus libmodbus-dev libmicrohttpd libmicrohttpd-dev; fi

script: 
  - mkdir build && cd build && cmake -DFULL=ON ..
  - make
  #- make package #can turn this on when we do a deploy step
  - build/ODC_tests
  #- build/DNP3Port_tests #opendnp3 bug makes this hang at the moment
  - build/MD3Port_tests
  
