version: 0.4.0.{build}
branches:
  only:
  - develop
#  - master
#  - /^release\/.*$/
os: Visual Studio 2017


#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration:
 - Release
 - Debug

matrix:
  - platform: x86
    cpu_bits: 32
    cmake_generator: build-win32
    cmake_platform: win32
  - platform: x64
    cpu_bits: 64
    cmake_generator: build-win64
    cmake_platform: win64
 
clone_folder: C:\projects\opendatacon
environment:
  MICROHTTPD_HOME: C:\libmicrohttpd\libmicrohttpd-0.9.17-w32
  MODBUS_HOME: C:\libmodbus\libmodbus\windows32
  
init:
    
install:
- ps: >-
    If (-not (Test-Path C:\libmodbus\libmodbus)){
      Start-FileDownload "https://www.dropbox.com/s/iqf95y9x1x4ol36/libmodbus.zip?dl=1" -FileName libmodbus.zip
      7z x -y libmodbus.zip
      New-Item C:\libmodbus -ItemType Directory
      Move-Item .\libmodbus C:\libmodbus\libmodbus
    }
- ps: >-
    If (-not (Test-Path C:\libmicrohttpd\libmicrohttpd-w32)){
      Start-FileDownload "https://ftp.yzu.edu.tw/pub/gnu/libmicrohttpd/libmicrohttpd-0.9.17-w32.zip" -FileName libmicrohttpd-w32.zip
      7z x -y libmicrohttpd-w32.zip
      New-Item C:\libmicrohttpd -ItemType Directory
      Move-Item .\libmicrohttpd-w32 C:\libmicrohttpd\libmicrohttpd-w32
    }
cache:
- C:\libmodbus\
- C:\libmicrohttpd\
- C:\projects\opendatacon\submodules

before_build:
- cmd: cd C:\projects\opendatacon
- cmd: cmake . -B%cmake_generator% -DFULL=ON -DMODBUS_HOME=c:\libmodbus\libmodbus\windows%cpu_bits% -DMICROHTTPD_HOME=C:\libmicrohttpd\libmicrohttpd-%cpu_bits%
#build:
#  parallel: true                  # enable MSBuild parallel builds
#  project: build-win32\opendatacon_suite.sln      # path to Visual Studio solution or project
build_script:
- cmd: msbuild %cmake_generator%\opendatacon_suite.sln /p:Configuration=%configuration% /p:Platform=%cmake_platform%
test_script:
- cmd: '%cmake_generator%\%configuration%\ODC_tests.exe'
#- cmd: '%cmake_generator%\%configuration%\DNP3Port_tests.exe' #opendnp3 bug makes this hang at the moment
- cmd: '%cmake_generator%\%configuration%\MD3Port_tests.exe'
