version: 0.4.0.{build}
branches:
  only:
  - develop
#  - master
#  - /^release\/.*$/
os: Visual Studio 2017
configuration: Release
platform: x86
clone_folder: C:\projects\opendatacon
environment:
  MICROHTTPD_HOME: C:\libmicrohttpd\libmicrohttpd-0.9.17-w32
  MODBUS_HOME: C:\libmodbus\libmodbus\windows32
install:
- ps: >-
    If (-not (Test-Path C:\libmodbus\libmodbus)){
      Start-FileDownload "https://www.dropbox.com/s/iqf95y9x1x4ol36/libmodbus.zip?dl=1" -FileName libmodbus.zip
      7z x -y libmodbus.zip
      New-Item C:\libmodbus -ItemType Directory
      Move-Item .\libmodbus C:\libmodbus\libmodbus
    }
- ps: >-
    If (-not (Test-Path C:\libmicrohttpd\libmicrohttpd-0.9.17-w32)){
      Start-FileDownload "https://www.dropbox.com/s/13t92f57wie4wnb/libmicrohttpd-0.9.17-w32.zip?dl=1" -FileName libmicrohttpd-0.9.17-w32.zip
      7z x -y libmicrohttpd-0.9.17-w32.zip
      New-Item C:\libmicrohttpd -ItemType Directory
      Move-Item .\libmicrohttpd-0.9.17-w32 C:\libmicrohttpd\libmicrohttpd-0.9.17-w32
    }
cache:
- C:\libmodbus\
- C:\libmicrohttpd\
before_build:
- cmd: cd C:\projects\opendatacon
- cmd: cmake . -Bbuild-win32 -DFULL=ON -DMODBUS_HOME=c:\libmodbus\libmodbus\windows32 -DMICROHTTPD_HOME=C:\libmicrohttpd\libmicrohttpd-0.9.17-w32
build:
  parallel: true                  # enable MSBuild parallel builds
  project: build-win32\opendatacon_suite.sln      # path to Visual Studio solution or project
#build_script:
#- cmd: msbuild build-win32\opendatacon_suite.sln /p:Configuration=Release /p:Platform=Win32
test_script:
- cmd: build-win32\ODC_tests
#- cmd: build\DNP3Port_tests #opendnp3 bug makes this hang at the moment
- cmd: build-win32\MD3Port_tests
