name: opendatacon workflow

on:
  push:
    branches:
      - '**' # matches every branch

jobs:
  opendatacon-build-matrix:
  
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-type: [Release,Debug]
        
    runs-on: ${{ matrix.os }}
    
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      INSTALL_PREFIX: ${{github.workspace}}/build/install
      LOG_LVL: error
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - if: contains(matrix.os,'macos')
      name: Set MacOS env
      run: echo Set MacOS env
      env:
        TOOLCHAIN_OPT: -DPACKAGE_DNP3=OFF -DPACKAGE_LIBMICROHTTPD=OFF -DPACKAGE_LIBMODBUS=OFF -DPACKAGE_PYTHON=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
        
    - if: contains(matrix.os,'ubuntu')
      name: Set Ubuntu env
      run: echo Set Ubuntu env
      env:
        SYSVER_OPT: -DCMAKE_SYSTEM_VERSION=generic

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PREFIX}} ${{env.TOOLCHAIN_OPT}} ${{env.SYSVER_OPT}} -DTESTS=ON -DWEBUI=ON -DJSONPORT=ON -DSIMPORT=ON -DMD3PORT=ON -DCBPORT=ON -DCONSOLEUI=ON -DDNP3PORT=ON
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j8
      
    - name: Package
      working-directory: ${{github.workspace}}/build
      run: make package
      
    - name: Install
      working-directory: ${{github.workspace}}/build
      run: make install
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        install/bin/ODC_tests ${{env.LOG_LVL}} -d yes
        install/bin/DNP3Port_tests ${{env.LOG_LVL}} -d yes
        install/bin/SimPort_tests -d yes
        install/bin/MD3Port_tests ${{env.LOG_LVL}} -d yes
        install/bin/CBPort_tests ${{env.LOG_LVL}} -d yes
        install/bin/Integration_tests ${{env.LOG_LVL}} -d yes
        
        
        
