name: opendatacon workflow

on:
  push:
    branches:
      - '**' # matches every branch

jobs:
  opendatacon build matrix:
  
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-type: [Release,Debug]
        
    runs-on: ${{ matrix.os }}
    
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j8
      
    - name: Package
      working-directory: ${{github.workspace}}/build
      run: make package
      
